project_name: captain

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/captain/
    binary: captain
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

snapcrafts:
  - summary: Convert your Git workflow to Docker containers ready for Continuous Delivery.
    description: |
      This is the best drum roll application out there.
      Install it and awe!
    grade: stable
    confinement: strict
    apps:
      captain:
        plugs: ["home", "docker", "system-files"]
    plugs:
      system-files:
        write: ["/var/run/docker.sock"]
brews:
  - github:
      owner: guilhem
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@barpilot.io
    homepage: "https://github.com/guilhem/captain"
    description: "Convert your Git workflow to Docker containers ready for Continuous Delivery."
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries: ["captain"]
    image_templates:
      - "barpilot/captain:latest"
      - "barpilot/captain:{{ .Tag }}"
      - "barpilot/captain:{{ .Major }}"
    dockerfile: Dockerfile.goreleaser
